kubernetes/machine-class.yaml, pkg/azure/core.go, pkg/azure/core_test.go, pkg/azure/utils.go
This PR adds a check to verify that the MachineClass being passed for MachineCreation, Deletion and other driver methods belongs to the relevant cloud provider
Fixes [#599](https://github.com/gardener/machine-controller-manager/issues/599)
```improvement user
NONE
```
=> add a check on provider of the machineclass in the driver methods

pkg/azure/core.go, pkg/azure/core_test.go
This PR introduces error handling of the `decodeProviderSpecAndSecret()` in the `ListMachines()` driver method
Fixes #21 
```improvement user
NONE
```
=> handle decodeProviderSpecAndSecret error in ListMachines

pkg/azure/core.go, pkg/azure/core_test.go
The PR fixes regressions that were missed during migration to OOT drivers.
It caries over the changes for the azure_driver.go file on this [MCM PR 509](https://github.com/gardener/machine-controller-manager/pull/509/files#diff-36365e28193d28c39f36ac4d9172fbf8eac69553361f6179fa3184f9cad9eb0cR46-R1178)
Fixes #
A regression that I noticed while trying to drain kubernetes clusters using CSI volumes on Azure
```noteworthy user
Fixes regressions fetching volumeIDs to Azure CSI volumes
```
=> Fixes regressions while fetching CSI volume-IDs

pkg/azure/core.go, pkg/azure/core_test.go, pkg/azure/core_utils.go, pkg/azure/utils.go, vendor/modules.txt
This PR isolates the providerSpec field and Secret field from the Driver object.
Fixes [#304](https://github.com/gardener/gardener-extension-provider-azure/issues/304)
```bugfix developer
A shared data structure was causing race conditions leading to VM creation with wrong configurations.
```
=> A shared data structure was causing race conditions leading to VM creation with wrong configurations.

.ci/pipeline_definitions
Updates the test machinery images in the pipeline definition
Fixes #
I have referred the pipeline definition from [MCM-Provider-AWS](https://github.com/gardener/machine-controller-manager-provider-aws)
```improvement developer
NONE
```
=> update pipeline definitions with test machinery image

.ci/test
Recently there has been a major version jump in ginkgo, due to which tests are failing.
This PR will enable use of latest v1.16.5 of ginkgo for tests.
`go install` is used as it doesn't affect go.mod and `go get` doesn't support getting a particular version without affecting go.mod.
```improvement user
Ginkgo version 1.16.5 is used for tests until changes compatible with v2.0.0 are made.
```
=> Use ginkgo v1 for tests

Makefile, kubernetes/deployment.yaml
Allows to run IT in a way where controllers are run inside the cluster as containers.
Fixes #
```improvement user
Updates deployment YAML used in IT when controllers are run as containers in the cluster.
```
=> Update deployment YAML used in IT

pkg/azure/core.go, pkg/azure/core_test.go, pkg/azure/utils.go
The deletion of a machine will be blocked in case the underlying resource group is not available on Azure.
The `DeleteMachine()` function is already checking if the resource group is available and if not the deletion flow will be aborted.
During the deletion flow the `ListMachines()` function is also called by other means e.g. safety controller and the list machine call towards Azure will fail if the resource group is gone. As result mcm-provider-azure is not able to complete the machine deletion.
This PR adds the resource group availability check also to the `ListMachines()` function in addition to the `DeleteMachine()` function.
Fixes #19
```improvement …
```
=> Abort `ListMachines` call if resource group is gone.

kubernetes/machine-class.yaml, pkg/azure/apis/azure_provider_spec.go, pkg/azure/apis/validation/validation.go, pkg/azure/apis/validation/validation_test.go, pkg/azure/utils.go
- Add support for machines based on shared gallery images
Fixes #71 
SharedGalleryImageID eg:- `/SharedGalleries/<sharedGalleryName>/Images/<sharedGalleryImageName>/Versions/<sharedGalleryImageVersionName>`
```improvement user
Machine-Controller-Manager Provider-Azure now supports managing virtual machines based on shared image gallery images. 
```
/invite @himanshu-kun
=> Add support for sharedGalleryImageID in azure image reference

pkg/azure/utils.go
This PR handles the error returned by the `waitForDataDiskDetachment` method, which detaches the data disk before deleting the VM itself.
Fixes #
```improvement user
error handling is done for data disk detachment failure.
```
=> Handle data disk detachment failure error

.ci/pipeline_definitions
Add cve categorization for mcm-provider-azure.
The categorization was initially defined here and it transferred as defined to the mcm-provider-azure repository: 
https://github.com/gardener/gardener-extension-provider-azure/pull/621 
We move the cve categorization to the mcm-provider-azure repository as the categorization can't be taken into consideration when it is defined in the respective provider extension project. Once this behaviour has changed we can remove the categorisation here again.
```other operator
CVE categorization for mcm-provider-azure has been added.
```
=> Add cve categorization for mcm-provider-azure

pkg/azure/core_test.go, pkg/azure/utils.go, pkg/azure/utils_test.go
This PR fixes creation and update of azure VMs when `sshAccess` is disabled by adding a "fake" `PublicKey`.
Currently, creating an azure shoot with `sshAccess` disabled is not possible since the shoot would fail in reconciliation. It fails with the following cloud provider validation error: `The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.` since its value is "".
After removing `SSH` from `LinuxConfiguration` it starts failing with this cloud provider error: `Authentication using either SSH or by user name and password must be enabled in Linux profile.`, which would suggest we need to provide either `SSH` or an `adminPassword`. We do not include the `adminPassword` and it is ill-advised to do so. The only option left …
=> Fix VM creation and update when `sshAccess` is disabled.

pkg/azure/core.go, pkg/azure/utils.go
This PR removes the usage of the `defer` keyword when printing logs in some of the methods. Deferred logging leads to confusing logs, as the logged statement is incorrect when the corresponding method has to return an error.
Fixes #
```improvement operator
removed the use of `defer` in printing logs for resource creation methods
```
=> Automated cherry pick of #87: remove use of defer in printing logs

go.mod, pkg/azure/access/helpers/disk.go, pkg/azure/access/helpers/marketplaceagreement.go, pkg/azure/access/helpers/nic.go, pkg/azure/access/helpers/resourcegraph.go, pkg/azure/access/helpers/resourcegroup.go, pkg/azure/access/helpers/subnet.go, pkg/azure/access/helpers/vm.go, pkg/azure/access/helpers/vmimage.go, pkg/azure/api/validation/validation.go, pkg/azure/instrument/instrument.go, pkg/azure/instrument/instrument_test.go, pkg/azure/provider/provider.go, pkg/azure/provider/provider_test.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go, vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go, vendor/modules.txt
Fixes #129 
```improvement user
Fixed recording of erroneous metrics for driver and API requests
```
=> Fixed recording of erroneous metrics for driver and API requests

pkg/azure/provider/helpers/driver.go, pkg/azure/provider/provider.go, pkg/azure/provider/provider_test.go
Fixes #131 
```other operator
Fixed handling for data disk in ToBeDetached=true state during vm deletion
```
=> Fixed handling for data disk in tobedetached state during vm deletion

pkg/azure/provider/helpers/driver.go, pkg/azure/provider/provider_test.go, pkg/azure/testhelp/fakes/clusterstate.go
Fixes #133 
```improvement operator
Fixed the gap where VM marketplace images with no plans were not handled properly. Now one can start VMs having marketplace image with no plan.
```
=> Handle MarketPlaceImages with no purchase plan defined as valid case

kubernetes/machine-class.yaml, pkg/azure/api/providerspec.go, pkg/azure/provider/helpers/driver.go
- Add support to enable vm boot diagnostics
Fixes #104 
```improvement user
Machine-Controller-Manager Provider-Azure now supports enabling of vm boot diagnostics. 
```
=> Add support for vm boot diagnostic profile

.ci/pipeline_integration_test
Update kubeconfig expiry to 24hrs for pipeline tests
Fixes #
```improvement user
NONE
```
=> Update kubeconfig expiry to 24hrs for pipeline tests

pkg/azure/provider/helpers/driver.go, pkg/azure/provider/provider.go, pkg/azure/provider/provider_test.go, pkg/azure/testhelp/fakes/machineresources.go
This PR fixes a bug in the DeleteMachine function where cascade delete option was set for all resources attached to the VM. It should be set only for the resources that were created as a part of VM creation.
Fixes #
```improvement user
Bugfix:- During VM deletion, the cascade delete option is set only for the resources part of VM creation. 
```
=> Do not set cascade delete for resources not part of VM creation

pkg/azure/provider/helpers/driver.go, pkg/azure/provider/provider.go, pkg/azure/provider/provider_test.go, pkg/azure/testhelp/fakes/machineresources.go
Cherry-pick PR of #142
Fixes #
```improvement user
Bugfix:- During VM deletion, the cascade delete option is set only for the resources part of VM creation. 
```
=> Cherry-pick PR of #142

pkg/azure/api/providerspec.go, pkg/azure/api/validation/validation.go, pkg/azure/api/validation/validation_test.go, pkg/azure/provider/helpers/driver.go, pkg/azure/testhelp/fakes/machineresources.go, pkg/azure/testhelp/providerspec.go, pkg/azure/utils/names.go, pkg/azure/utils/names_test.go
The documentation states that `dataDisk.Lun` is required.
Therefore it makes more sense to use a value instead of pointer.
Fixes #
```improvement developer
Switch AzureDataDisk.Lun from pointer to value
```
=> Switch data disk lun from pointer to value

Makefile
This PR provides a flag to specify target platform for the docker image
Fixes #https://github.com/gardener/machine-controller-manager/issues/921
```improvement user
```
=> fixes docker image

pkg/azure/access/factory.go
This PR is a follow-up to #148. Due to an oversight, the previous change caused only the authentication to connect to the intended cloud.
I've obtained some credentials for other Instances in the meantime and was able to verify that with these changes, creating Machines on other Providers can succeed.
I've gone ahead and made the passed ConnectConfig the source of truth for the connection-options. One could think about merging it with the factory-provided options, but since these are currently _always_ the default options I've decided not to do this for now.
```noteworthy user
Fixed a bug that prevented everything but authentication from connecting to non-public Azure Cloud instances.
```
=> Always use passed ConnectConfig when creating clients

.ci/pipeline_definitions, Dockerfile, go.mod, pkg/azure/provider/helpers/driver.go
Fixes #
```improvement user
Golang version upgraded to `1.22.5`
```
=> Update go version to 1.22.5

pkg/azure/access/factory.go
Always use passed ConnectConfig when creating clients
Fixes #
```noteworthy user github.com/gardener/machine-controller-manager-provider-azure #157 @AndreasBurger 
Fixed a bug that prevented everything but authentication from connecting to non-public Azure Cloud instances.
```
=> [Cherry-pick rel-v0.13] Merge pull request #157 from AndreasBurger/az-clouds-pt2

pkg/azure/access/helpers/disk.go, pkg/azure/api/providerspec.go, pkg/azure/api/validation/validation.go, pkg/azure/api/validation/validation_test.go, pkg/azure/provider/helpers/connectconfig_test.go, pkg/azure/provider/helpers/driver.go, pkg/azure/provider/helpers/resourcegraphprocessor.go, pkg/azure/provider/provider.go, pkg/azure/testhelp/fakes/machineresources.go, pkg/azure/testhelp/providerspec.go, pkg/azure/utils/images.go, pkg/azure/utils/images_test.go, pkg/azure/utils/names.go, pkg/azure/utils/names_test.go
Adds the ability to attach dataDisks with image references.
Related to: https://github.com/gardener/gardener-extension-provider-azure/issues/788
For now it's not possible to create a dataDisk with imageReference afaik.
Therefore we create a general Disk with the imageReference before creating the VM.
This disk is then attached in the VM creation process.
```improvement user
Adds the ability to attach dataDisks with image references
```
=> Data disk image reference for vsmp

pkg/azure/access/errors/errors.go
This PR maps the following errors returned by Azure during VM creation to the `ResourceExhausted` error code.
1. SkuNotAvailable
2. AllocationFailed
3. ResourceQuotaExceeded
Fixes #187 
```improvement operator
SkuNotAvailable error is now mapped to ResourceExhausted error code
```
```improvement operator
AllocationFailed error is now mapped to ResourceExhausted error code
```
```improvement operator
ResourceQuotaExceeded error is now mapped to ResourceExhausted error code
```
=> Map Azure error codes to `ResourceExhausted` error code
